CREATE DATABASE store default charset utf8;

USE store;

CREATE TABLE category
(
    category_id INT AUTO_INCREMENT,
    parent_category_id INT,
    name varchar(255) NOT NULL,
    description text,

    CONSTRAINT category_pk PRIMARY KEY (category_id),

    CONSTRAINT category_category_fk
        FOREIGN KEY (parent_category_id)
        REFERENCES category(category_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE image
(
    image_id INT AUTO_INCREMENT,
    path varchar(255) NOT NULL,
    alt varchar(255),

    CONSTRAINT image_pk PRIMARY KEY(image_id)
);

CREATE TABLE product
(
    product_id INT AUTO_INCREMENT,
    name varchar(255) NOT NULL,
    main_category_id INT NOT NULL,
    main_image_id INT NOT NULL,
    description text,
    price decimal(8,2) NOT NULL,
    price_with_sale decimal(8,2),
    price_with_promo decimal(8,2),
    is_active boolean DEFAULT true,

    CONSTRAINT product_pk PRIMARY KEY(product_id),
    CONSTRAINT product_category_fk
        FOREIGN KEY (main_category_id)
        REFERENCES category(category_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT product_image_fk
        FOREIGN KEY (main_image_id)
        REFERENCES image(image_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CHECK (price >= 0 AND price_with_sale >= 0 AND price_with_promo >= 0)
);

CREATE TABLE product_categories
(
    product_id INT NOT NULL,
    category_id INT NOT NULL,

    CONSTRAINT pc_pk PRIMARY KEY (product_id, category_id),

    CONSTRAINT pc_product_fk
        FOREIGN KEY (product_id)
        REFERENCES product(product_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT pc_category_fk
        FOREIGN KEY (category_id)
        REFERENCES category(category_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE images
(
    product_id INT NOT NULL,
    image_id INT NOT NULL,

    CONSTRAINT images_pk PRIMARY KEY (product_id, image_id),
    CONSTRAINT images_image_fk
        FOREIGN KEY(image_id)
        REFERENCES image(image_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT images_product_fk
        FOREIGN KEY(product_id)
        REFERENCES product(product_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

# ------ Fill table category
INSERT INTO category(name, description)
    VALUE ('Рубашки', 'Lorem ipsum dolor sit amet, urpis sagittis lorem');

INSERT INTO category(parent_category_id, name, description)
    VALUES (1, 'Рубашки Medicine', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
           (2, 'Все модели Medicine', 'Lorem ipsum dolor sit amet, consectetur');

INSERT INTO category(name, description)
    VALUE ('Джинсы', 'Lorem ipsum dolor');

INSERT INTO category(parent_category_id, name)
    VALUE (4, 'Джинсы Levi`s');
# ------

# ------ Fill table image
INSERT INTO image(path, alt)
    VALUES ('img/photos/img1.png', 'Зелёная Рубашка Medicine на белом фоне'),
           ('img/photos/img2.png', 'Девушка в зелёной рубашке Medicine в полный рост'),
           ('img/photos/img3.png', 'Девушка в зелёной рубашке Medicine'),
           ('img/photos/img4.png', 'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor'),
           ('img/photos/img5.png', 'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor'),
           ('img/photos/img6.png', 'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor'),
           ('img/photos/img7.png', 'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor'),
           ('img/photos/img8.png', 'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor'),
           ('img/photos/img9.png', 'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor'),
           ('img/photos/img10.png', 'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor'),
           ('img/photos/img11.png', 'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor');
# ------

# ------ Fill table product
INSERT INTO product(name, main_category_id, main_image_id, description, price, price_with_sale, price_with_promo, is_active)
    VALUES ('Рубашка Medicine',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 1',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 2',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 3',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            false),
           ('Рубашка Medicine 4',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 5',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 6',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 7',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 8',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 9',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 10',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 11',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 12',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true),
           ('Рубашка Medicine 13',
            2,
            1,
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            2666,
            2499,
            2227,
            true);

INSERT INTO product(name, main_category_id, main_image_id, description, price, price_with_sale, price_with_promo, is_active)
    VALUES ('Рубашка обычная',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 1',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 2',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            false),
           ('Рубашка обычная 3',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            false),
           ('Рубашка обычная 4',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 5',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 6',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 7',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 8',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 10',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 11',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 12',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 13',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 14',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true),
           ('Рубашка обычная 15',
            1,
            4,
            ' Ut sed rutrum lectus, quis facilisis ex.',
            1600,
            1500,
            1300,
            true);

INSERT INTO product(name, main_category_id, main_image_id, description, price, price_with_sale, price_with_promo, is_active)
    VALUES ('Джинсы Levi`s',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 1',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 2',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            false),
           ('Джинсы Levi`s 3',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            false),
           ('Джинсы Levi`s 4',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 5',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 6',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 7',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 8',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 9',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 10',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 11',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 12',
            5,
            7,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4000,
            3500,
            3200,
            true),
           ('Джинсы Levi`s 13',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 14',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 15',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 16',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 17',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 18',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 19',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 20',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            false),
           ('Джинсы Levi`s 21',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 22',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            false),
           ('Джинсы Levi`s 23',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 24',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 25',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true),
           ('Джинсы Levi`s 26',
            5,
            9,
            'Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor',
            4200,
            3600,
            3300,
            true);

# ------

# ------ Fill table images
INSERT INTO images(product_id, image_id)
    VALUES (1, 1),
           (1, 2),
           (1, 3),
           (2, 1),
           (2, 2),
           (2, 3),
           (3, 1),
           (3, 2),
           (3, 3),
           (4, 1),
           (4, 2),
           (4, 3),
           (5, 1),
           (5, 2),
           (5, 3),
           (6, 1),
           (6, 2),
           (6, 3),
           (7, 1),
           (7, 2),
           (7, 3),
           (8, 1),
           (8, 2),
           (8, 3),
           (9, 1),
           (9, 2),
           (9, 3),
           (10, 1),
           (10, 2),
           (10, 3),
           (11, 1),
           (11, 2),
           (11, 3),
           (12, 1),
           (12, 2),
           (12, 3),
           (13, 1),
           (13, 2),
           (13, 3),
           (14, 1),
           (14, 2),
           (14, 3);

INSERT INTO images(product_id, image_id)
    VALUES (15, 4),
           (15, 5),
           (15, 6),
           (16, 4),
           (16, 5),
           (16, 6),
           (17, 4),
           (17, 5),
           (17, 6),
           (18, 4),
           (18, 5),
           (18, 6),
           (19, 4),
           (19, 5),
           (19, 6),
           (20, 4),
           (20, 5),
           (20, 6),
           (21, 4),
           (21, 5),
           (21, 6),
           (22, 4),
           (22, 5),
           (22, 6),
           (23, 4),
           (23, 5),
           (23, 6),
           (24, 4),
           (24, 5),
           (24, 6),
           (25, 4),
           (25, 5),
           (25, 6),
           (26, 4),
           (26, 5),
           (26, 6),
           (27, 4),
           (27, 5),
           (27, 6),
           (28, 4),
           (28, 5),
           (28, 6),
           (29, 4),
           (29, 5),
           (29, 6);

INSERT INTO images(product_id, image_id)
    VALUES (30, 7),
           (30, 8),
           (31, 7),
           (31, 8),
           (32, 7),
           (32, 8),
           (33, 7),
           (33, 8),
           (34, 7),
           (34, 8),
           (35, 7),
           (35, 8),
           (36, 7),
           (36, 8),
           (37, 7),
           (37, 8),
           (38, 7),
           (38, 8),
           (39, 7),
           (39, 8),
           (40, 7),
           (40, 8),
           (41, 7),
           (41, 8),
           (42, 7),
           (42, 8);

INSERT INTO images(product_id, image_id)
    VALUES (43, 9),
           (43, 10),
           (43, 11),
           (44, 9),
           (44, 10),
           (44, 11),
           (45, 9),
           (45, 10),
           (45, 11),
           (46, 9),
           (46, 10),
           (46, 11),
           (47, 9),
           (47, 10),
           (47, 11),
           (48, 9),
           (48, 10),
           (48, 11),
           (49, 9),
           (49, 10),
           (49, 11),
           (50, 9),
           (50, 10),
           (50, 11),
           (51, 9),
           (51, 10),
           (51, 11),
           (52, 9),
           (52, 10),
           (52, 11),
           (53, 9),
           (53, 10),
           (53, 11),
           (54, 9),
           (54, 10),
           (54, 11),
           (55, 9),
           (55, 10),
           (55, 11),
           (56, 9),
           (56, 10),
           (56, 11);
# ------

# ------ Fill table product_categories
INSERT INTO product_categories(product_id, category_id)
    VALUES (1, 2),
           (1, 1),
           (1, 3),
           (2, 2),
           (2, 1),
           (2, 3),
           (3, 2),
           (3, 1),
           (3, 3),
           (4, 2),
           (4, 1),
           (4, 3),
           (5, 2),
           (5, 1),
           (5, 3),
           (6, 2),
           (6, 1),
           (6, 3),
           (7, 2),
           (7, 1),
           (7, 3),
           (8, 2),
           (8, 1),
           (8, 3),
           (9, 2),
           (9, 1),
           (9, 3),
           (10, 2),
           (10, 1),
           (10, 3),
           (11, 2),
           (11, 1),
           (11, 3),
           (12, 2),
           (12, 1),
           (12, 3),
           (13, 2),
           (13, 1),
           (13, 3),
           (14, 2),
           (14, 1),
           (14, 3),
           (15, 1),
           (16, 1),
           (17, 1),
           (18, 1),
           (19, 1),
           (20, 1),
           (21, 1),
           (22, 1),
           (23, 1),
           (24, 1),
           (25, 1),
           (26, 1),
           (27, 1),
           (28, 1),
           (29, 1),
           (30, 4),
           (30, 5),
           (31, 4),
           (31, 5),
           (32, 4),
           (32, 5),
           (33, 4),
           (33, 5),
           (34, 4),
           (34, 5),
           (35, 4),
           (35, 5),
           (36, 4),
           (36, 5),
           (37, 4),
           (37, 5),
           (38, 4),
           (38, 5),
           (39, 4),
           (39, 5),
           (40, 4),
           (40, 5),
           (41, 4),
           (41, 5),
           (42, 4),
           (42, 5),
           (43, 4),
           (43, 5),
           (44, 4),
           (44, 5),
           (45, 4),
           (45, 5),
           (46, 4),
           (46, 5),
           (47, 4),
           (47, 5),
           (48, 4),
           (48, 5),
           (49, 4),
           (49, 5),
           (50, 4),
           (50, 5),
           (51, 4),
           (51, 5),
           (52, 4),
           (52, 5),
           (53, 4),
           (53, 5),
           (54, 4),
           (54, 5),
           (55, 4),
           (55, 5),
           (56, 4),
           (56, 5);
# ------
